version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels: ["dependencies"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    labels: ["dependencies"]
