services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -lc "sleep infinity"
    ports:
      - "3876:3876"
    environment:
      - NODE_ENV=development
    volumes:
      - ../../client:/app
    networks:
      - appnet

networks:
  appnet:
    driver: bridge