services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -lc "sleep infinity"
    ports:
      - "3876:3876"
    environment:
      - NODE_ENV=development
    volumes:
      - ../../client:/app
      - node_modules:/app/node_modules
      - npm_cache:/root/.npm
    networks:
      - appnet

volumes:
  npm_cache:
  node_modules:

networks:
  appnet:
    driver: bridge
