FROM node:20-alpine AS builder
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml ./
COPY apps ./apps

RUN pnpm install --frozen-lockfile
RUN pnpm --filter web... build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production PORT=3876
COPY --from=builder /app/apps/web/.next/standalone ./
COPY --from=builder /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=builder /app/apps/web/public ./apps/web/public
EXPOSE 3876
CMD ["node", "apps/web/server.js"]
